name: Ci
#https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master] #branches precisam ser array dessa forma

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Save cache
        #https://github.com/actions/cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run tests react and styles
        uses: actions/setup-node@v2
        with:
          node-version: '16.*'
      # a docs pede nesse formato os run #https://github.com/actions/setup-node
      - run: node --version
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage # esse -- e para adicionar mais uma flag importante no pack.json so tem npm run test
        env:
          CI: true
      - name: Upload artifacts
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: code coverage # nome que vai aparecer para fazer download na interface do git hub
          path: coverage
      - name: Run build
        # if precisa estar dentro do name
        if: github.event_name == 'push'
        run: |
          npm ci
          npm run build
      - name: Create release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - uses: actions/download-artifact@v2
      - name: Deploy project
        if: github.event_name == 'push'
        run: |
          npm install --global surge
          surge --project ./build --domain gitactionskenji231.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
