name: Ci
#https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master] #branches precisam ser array dessa forma

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Save cache
        #https://github.com/actions/cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run tests react and styles
        uses: actions/setup-node@v2
        with:
          node-version: '16.*'
      # a docs pede nesse formato os run #https://github.com/actions/setup-node
      - run: node --version
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage # esse -- e para adicionar mais uma flag importante no pack.json so tem npm run test
        env:
          CI: true
      - name: Upload artifacts
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: code coverage # nome que vai aparecer para fazer download na interface do git hub
          path: coverage
      - name: Run build
        # if precisa estar dentro do name
        if: github.event_name == 'push'
        run: |
          npm ci
          npm run build
      - name: Zip assets release
        # primeiro precisa fazer o assets depois release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          zip -r  build.zip  ./build
          zip -r  coverage.zip ./coverage
      - name: Create release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          # github fornece um token assim que inicia aplicação, consigo acessar direto por secrets.GITHUB.TOKEN
          # mas criei um novo token,porque o evento de release precisa ser meu usuário e nao criado pelo github
          # para criar seu token,no seu perfil de usuário do github,procura por settings, Developer settings e gera o token
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - uses: actions/download-artifact@v2
      - name: Deploy to staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          npm install --global surge
          surge --project ./build --domain gitactionskenji231.surge.sh
          echo $SURGE_TOKEN
      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          npm install --global surge
          surge --project ./build --domain gitactionskenji231.surge.sh
      - name: Upload coverage reports
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
