name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.*'
      - name: Build app react
        run: |
          npm --version
          npm ci
          npm run format
          npm run test
        env:
          CI: 'true'
