name: CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop] #tem que ser assim

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test react and styles format
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.*' # a docs pede assim #https://github.com/actions/setup-node
      - run: npm --version
      - run: npm ci
      - run: npm run format:check
      - run: npm run test --coverage
        env: # essa variavel vai ser encontrada de forma automatica no test
          CI: true
      - name: Run build
        if: github.event_name == 'push' # if precisa estar dentro do name
        run: npm run build
      - name: Deploy Project
        if: github.event_name == 'push'
        run: |
          npm install --global surge
          surge project ./build --domain gitactionskenji231
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
